name: Uninstall a Helm chart
# ref: https://docs.github.com/en/actions/deployment/deploying-to-your-cloud-provider/
description: Uninstall a Helm chart
author: Denis Trofimov denis.trofimov@huma.com
branding:
  color: 'purple'
  icon: 'x-square'
inputs:
  project_id:
    description: GCP project ID
    required: true
  cluster_name:
    description: GKE cluster name
    required: true
  gcp_credentials:
    description: GCP Service Account Key
    required: true
  location:
    description: GKE zone
    required: true
  app_name:
    description: Application Deployment name
    required: true
  app_namespace:
    description: Application namespace
    required: true
  delete_namespace:
    description: Delete namespace
    required: false
    default: 'false'

runs:
  using: composite
  steps:
    - name: Setup gcloud CLI
      uses: google-github-actions/setup-gcloud@v0
      with:
        service_account_key: ${{ inputs.gcp_credentials }}
        project_id: ${{ inputs.project_id }}

    - name: Get the GKE credentials so we can deploy to the cluster
      uses: google-github-actions/get-gke-credentials@v0
      with:
        cluster_name: ${{ inputs.cluster_name }}
        location: ${{ inputs.location }}
        credentials: ${{ inputs.gcp_credentials }}

    - name: Uninstall a Helm chart
      run: helm uninstall ${{ inputs.app_name }} -n ${{ inputs.app_namespace }}
      shell: bash

    - name: Delete namespace
      if: inputs.delete_namespace != 'false'
      run: kubectl delete namespace ${{ inputs.app_namespace }} --wait=false
      shell: bash
