name: Deploy a Helm chart to GKE
description: Deploy a Helm chart to GKE
author: Denis Trofimov denis.trofimov@huma.com
# ref: https://docs.github.com/en/actions/deployment/deploying-to-your-cloud-provider/
branding:
  color: 'purple'
  icon: 'upload-cloud'

inputs:
  project_id:
    description: GCP project ID
    required: true
  cluster_name:
    description: GKE cluster name
    required: true
  location:
    description: GKE zone
    required: true
  chart_url:
    description: Chart URL
    required: true
  app_name:
    description: Application Deployment name
    required: true
  version:
    description: Chart version
    required: true
  app_namespace:
    description: Application namespace
    required: true
  image_repository:
    description: Image repository
    required: true
  image_tag:
    description: Image tag
    default: latest
    required: false
  db_namespace:
    description: MongoDB Cluster Namespace
    required: true
  db_provider:
    description: MongoDB Cluster  provider
    required: true
  db_service:
    description: MongoDB Cluster service name
    required: true
  gcp_credentials:
    description: GCP Service Account Key to deploy workload
    required: true
  github_token:
    description: A Github token PAT
    required: true
outputs:
  result:
    description: helm's exit code
    value: ${{ steps.helm.outputs.result }}
runs:
  using: composite
  steps:
    - name: Setup gcloud CLI
      uses: google-github-actions/setup-gcloud@v0
      with:
        service_account_key: ${{ inputs.gcp_credentials }}
        project_id: ${{ inputs.project_id }}

    - name: Get the GKE credentials so we can deploy to the cluster
      uses: google-github-actions/get-gke-credentials@v0
      with:
        cluster_name: ${{ inputs.cluster_name }}
        location: ${{ inputs.location }}
        credentials: ${{ inputs.gcp_credentials }}

    # ref: https://helm.sh/docs/topics/registries/
    - name: Deploy a Helm chart
      id: helm
      env:
        HELM_EXPERIMENTAL_OCI: "1"
      run: |-
        echo ${{ inputs.github_token }} |\
          helm registry login -u ${{ github.actor }} --password-stdin ghcr.io
        helm upgrade ${{ inputs.app_name }} ${{ inputs.chart_url }} \
          -i --create-namespace -n ${{ inputs.app_namespace }} \
          --version ${{ inputs.version }} \
          --set image.repository=${{ inputs.image_repository }} \
          --set image.tag=${{ inputs.image_tag }} \
          --set fullnameOverride=${{ inputs.app_name }} \
          --set mongodb.clusterRef.name=${{ inputs.db_service }} \
          --set mongodb.clusterRef.namespace=${{ inputs.db_namespace }} \
          --set mongodb.provider=${{ inputs.db_provider }} && result=0 || result=$?
        echo "::set-output name=result::$result"
      shell: bash
